name: Gardevoir
version: 0.1.4
author: 'ExplosiveGameX Team'
main: ru.explosivegamex.gardevoir.GardevoirMain
depend: [WorldGuard]
commands:
   pvp:
      description: Command for a leave from pvp-arena
      usage: '&6&l/pvp leave &7- Покинуть pvp арену'
