name: Gardevoir
version: 0.3.0
author: 'ExplosiveGameX Team'
main: ru.explosivegamex.gardevoir.GardevoirMain
depend: [WorldGuard, WGRegionEvents, Essentials, PermissionsEx]
commands:
   pvp:
      description: Command for a leave from pvp-arena
      usage: '&6&l/pvp leave &7- Покинуть pvp-арену'
